import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { PackageX } from 'lucide-react';
import Image from 'next/image';
import Footer from './components/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex absolute top-0 left-0 right-0 flex-row justify-between items-center p-4">
          <div className="text-2xl font-bold">
            <Image src="/logo.svg" width={36} height={36} alt="logo" />
          </div>
          <div className="text-sm text-gray-500">User name</div>
        </div>
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
